name: cluster-analysis
channels:
  - defaults
dependencies:
  - ipython=7.1.1
  - matplotlib=3.0.1
  - numpy=1.15.4
  - pandas=0.23.4
  - pip
  - python=3.7.1
  - scikit-learn=0.20.1
  - spyder=3.3.2

